---
ft450d:
  setband: "BS"
  setfreqvfoa: "FA"
  setfreqvfob: "FB"
  setmode: "MD"
  setband: "BS"
  getband: "BS"
  getfreqvfoa: "GA"
  getfreqvfob: "GB"
  getmode: "GM"
  getvfo: "GV"
  setvfo: "VS"
