---
ft450d:
  commands:
    setband: "BS"
    setfreqvfoa: "FA"
    setfreqvfob: "FB"
    setmode: "MD"
    getband: "GS"
    getfreqvfoa: "FA;"
    getfreqvfob: "FB;"
    getmode: "MD0"
    getvfo: "VS"
    setvfo: "VS"
  modetable:
    1: "LSB"
    2: "USB"
    3: "CW"
    4: "FM"
    5: "AM"
    6: "DATA (RTTY-LSB)"
    7: "CW-R"
    8: "USER-L"
    9: "DATA (RTTY-USB)"
    B: "FM-N"
    C: "USER-U"
  bandtable:
    160m: "00"
    80m: "01"
    40m: "03"
    30m: "04"
    20m: "05"
    17m: "06"
    15m: "07"
    12m: "08"
    10m: "09"
    6m: "10"

