name: build
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.0' # The Go version to download (if necessary) and use.
      - run: go mod init catctl
      - run: go mod tidy
      - run: go build catctl
